#!/usr/bin/env bash
echo "creating new server file..."
ip=$(shuf -n 1 nordvpn-servers)
outfile=tmpserver.ovpn

cat nordvpn.ovpn | head -3 > $outfile
echo "remote $ip 443" >> $outfile
cat nordvpn.ovpn | tail +5 >> $outfile
echo "$ip ($outfile)"
